try {
    console.log("Hello")
    add(5)
    console.log("hii")
} catch (error) {
    console.log("Error-occured");
}
finally{

    console.log("Finally");
}